### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer-tooling/developer-platform-install#1]
I'm getting the following error when trying to compile the developer_platform_installer.iss:

Error on line 34 in Z:\installer\idp_source\idp.iss: [ISPP] Actual parameter Major is not of the declared type.
Compile aborted.

**Comment by kenfinnigan** [comment]
Is that a compile error while running the Dockerfile or using the Inno IDE?

**Comment by jrichter1** [comment]
This one is copied from the dockerfile run, but I did get the same problem from the IDE as well.

**Comment by kenfinnigan** [comment]
Closing as we're no longer using Inno
