### ISSUE TITLE
Make use of the progress bar when verifying checksums

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer-tooling/developer-platform-install#1012]
The verification may take a notable amount of time for multiple files. Use the progress bar to at least indicate how many components are done/left.

**Comment by dgolovin** [comment]
👍 I was thinking about doing install in three steps:
1. Verifying downloaded components
2. Downloading what is not downloaded or have not passed verification
3. Installing 

Currently (3) is done, but (1 - 2) joined in one with problem reported in this issue.
