### ISSUE TITLE
CDK description inconsistent with other components

### ISSUE THREAD

**Issue by robin-owen** [redhat-developer-tooling/developer-platform-install#1093]
At present, the description for CDK in the DevSuite installer is title cased. This is inconsistent with every other component of the installer.

Currently, the description reads as follows:

"Developer Tools for Creating, Testing, and Distributing Red Hat Container-Based Applications"

This is also a bit vague, not mentioning the fact that CDK runs a single-node OpenShift cluster in a local VM to assist with containerized application development.

**Comment by dgolovin** [comment]
I'll get in touch with CDK and doc team to update this description. The only problem space for it is extremely limited by just one line.

**Comment by dgolovin** [comment]
@LalatenduMohanty  Could you help with new description? It should be concise one line that would fit into the box shown below
![image](https://user-images.githubusercontent.com/620330/34279434-ad320d42-e665-11e7-98a3-c9d83b9ee616.png)

**Comment by dgolovin** [comment]
@LalatenduMohanty would that work?
![image](https://user-images.githubusercontent.com/620330/34807614-a2834684-f63e-11e7-93b1-fc25467b686c.png)

**Comment by LalatenduMohanty** [comment]
@dgolovin I would suggest "A container development environment to develop, run and test containerize applications on OpenShift Container Platform 3 locally"

**Comment by dgolovin** [comment]
@LalatenduMohanty sounds good, but that would look like this: 
![image](https://user-images.githubusercontent.com/620330/34828809-9973233e-f693-11e7-88a0-690a5afbf9f6.png)
@mohitsuman what do you think? Would that work from UI point of view?

**Comment by LalatenduMohanty** [comment]
@dgolovin It is looking long, more than what is expected. What about `Tool to develop applications on OpenShift Container Platform 3 locally` . @robin-owen WDTY?

**Comment by robin-owen** [comment]
@LalatenduMohanty At first glance, that seems both accurate and simple. Works for me. :)
