### ISSUE TITLE
A summary of what was installed should be displayed after a successful install

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#1108]
It would be helpful/informative to the user to see a summary/inventory of the components that were installed/updated successfully or failed.

![image](https://user-images.githubusercontent.com/620330/33754732-79d9d5d8-dba2-11e7-9425-454904edc3da.png)

Migrated form https://issues.jboss.org/browse/JBDS-3732 and https://issues.jboss.org/browse/JBDS-3965.

**Comment by dgolovin** [comment]
Final page should give directions where to go (links to docs or tutorials) or should let to start installed product(s).

**Comment by mohitsuman** [comment]
Fixed by #1360
