### ISSUE TITLE
Request for Administrator credentials should be shown once

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#1110]
Current implementation asks for administrator credentials for both vagrant and virtualbox installation. The request should be shown only once per installation.
Migrated from https://issues.jboss.org/browse/JBDS-4209.

**Comment by jrichter1** [comment]
Fixed as part of #1259. It is still possible for multiple dialogs to be produced, but that now depends on the OS settings.
