### ISSUE TITLE
Make the Select/Clear all buttons only affect the selected channel (?)

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer-tooling/developer-platform-install#1120]
Not quite sure how to approach this, but it feels weird these buttons will affect components you are not looking at. We could try to make them work for the selected channel only, that way what you see is what you get. Opinions?

**Comment by dgolovin** [comment]
Agreed, assigning to @sudhirverma.

**Comment by dgolovin** [comment]
Fixed in https://github.com/redhat-developer-tooling/developer-platform-install/pull/1172.
