### ISSUE TITLE
Request for administrator credentials should say DevSuite Installer not osascript

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#1131]
Current implementation use osascript (AppleScript Engine) to run installation for vagrant and virtualbox as administrator. The consequence is osascript name in standard login/password dialog.

![image](https://user-images.githubusercontent.com/620330/33922726-8510389c-df81-11e7-9849-ab377cccd2a5.png)

It should say Red Hat Development Suite Installer" instead.

Migrated from https://issues.jboss.org/browse/JBDS-4207.

**Comment by j00bar** [comment]
Or at the very least, the installer should warn that the authentication dialog will read osascript.

**Comment by jrichter1** [comment]
Fixed in #1259
