### ISSUE TITLE
Link in installer finish screen points to redundant instructions instead of "CDK how to"

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#1132]
Testing the Mac installer (online variant) and the finish screen that tells you to either open devstudio or see information about how to start using CDK points to this:
https://developers.redhat.com/products/devsuite/get-started/
This page has instructions to install devsuite, which is redundant because the finish screen indicates you already just did this. Not sure what this should point to, but it seems like this is probably not the correct page.

Migrated from https://issues.jboss.org/browse/JBDS-4218

**Comment by mohitsuman** [comment]
@LalatenduMohanty As shown in the last sprint review demo, the Get Started Link for CDK was pointing to https://developers.redhat.com/products/cdk/hello-world/ . But this does not give the user the exact documentation for CDK. 

While looking through the official documentation, can we point the link to this:
https://access.redhat.com/documentation/en-us/red_hat_container_development_kit

**Comment by LalatenduMohanty** [comment]
I think it should point to https://developers.redhat.com/products/cdk/hello-world/#cdk_build-your-first-app as that's the logical step for a user.

**Comment by LalatenduMohanty** [comment]
@dgolovin @mohitsuman The only think we need to make sure is that the link remains a permanent link else it will break the user experience.

**Comment by mohitsuman** [comment]
@LalatenduMohanty I have dropped a mail to Mike Guerette regarding this. Once he revert , will update the changes.
