### ISSUE TITLE
Installer Sets Path for Wrong User

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#1142]
When I run the offline installer from my non-privileged account, I am prompted by UAC for an administrator login. When I enter my admin login and proceed, tools like vagrant, etc. will not be available from the command line in my non-privileged account. It turns out, the necessary path entries were added to the user-specific path of the admin user, not the user starting the installer.

Migrated  from https://issues.jboss.org/browse/JBDS-3841.

**Comment by jrichter1** [comment]
Closing as out of date
