### ISSUE TITLE
VirtualBox should not be required to use CDK on MacOS if xhyve is present/working

### ISSUE THREAD

**Issue by j00bar** [redhat-developer-tooling/developer-platform-install#1159]
I downloaded and installed the CDK using the devsuite installer on my Mac, and it prompted me to upgrade my copy of VirtualBox. This was unnecessary, as my Mac already has docker-machine-xhyve installed and ready to go. The check for VirtualBox should also accept xhyve, so as not to insist upon a technology that may very well not be used.

**Comment by dgolovin** [comment]
Resolved with https://github.com/redhat-developer-tooling/developer-platform-install/pull/1303.
Implementation details are explained here https://github.com/redhat-developer-tooling/developer-platform-install/issues/1267.
