### ISSUE TITLE
CDK install via DevSuite Installer fails if minishift previously installed in /usr/local/bin

### ISSUE THREAD

**Issue by j00bar** [redhat-developer-tooling/developer-platform-install#1160]
I had previously installed minishift on my Mac using https://github.com/chouseknecht/minishift-up-role. This Ansible role installs Minishift with OpenShift Origin into `/usr/local/bin`. This breaks the DevSuite Installer, as it constructs its search path to prioritize `/usr/local/bin` before `/Applications/DeveloperSuite`.

![image](https://user-images.githubusercontent.com/166664/34085002-80170eea-e357-11e7-9ada-2e8982567814.png)

Perhaps the installer should check for the presence of `/usr/local/bin/minishift` first.

**Comment by dgolovin** [comment]
That can be fixed, but there still would be conflict between CDK and minishift (there is issue for that in CDK JIRA https://issues.jboss.org/browse/CDK-210).

**Comment by dgolovin** [comment]
fixed with https://github.com/redhat-developer-tooling/developer-platform-install/pull/1174
