### ISSUE TITLE
Download into a folder accessible by all users

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer-tooling/developer-platform-install#1243]
It does not make much sense to download everything each time a different (OS) user runs the installer on the same machine. Use a shared folder to store downloaded files.

**Comment by dgolovin** [comment]
That would be true for the same person using two user accounts on the same machine, but that is not always the case. By implementing this you basically shares all the binaries available on developers.redhat.com with all the users on the same machine where not every user even has developers program account.

I think this is clearly should not be implemented.
