### ISSUE TITLE
Installer don't proceed when Oracle VirtualBox 5.2.6 is already installed in windows box

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer-tooling/developer-platform-install#1258]
I got the latest release bits of Red Hat Container Development Kit for windows ```(Version: 3.3.0 for Windows)``` from [1] and started installation on my windows 10 box where i had Oracle VirtualBox 5.2.6. It stuck in ```selection``` tab i mean ```Next``` button is disabled. 

I am surprised with the validation message for VirtualBox, its clearly mentioned that ```... requires Oracle VirtualBox version 5.1.22 or higher...```, however it won't allow the installer to proceed though i have VirtualBox 5.2.6 is installed on my win10 setup. Moreover this is the only warning message i am seeing in ```selection``` tab.

Steps to reproduce : 
1. Download ```Red Hat Container Development Kit``` for windows ```(Version: 3.3.0 for Windows) from [1]
2. Once the download of devsuite-2.2.0-GA-bundle-installer.exe complete, start the installation
3. Proceed till ```selection``` tab to see the error mentioned above

[1] https://developers.redhat.com/downloads

![virtualboxerror](https://user-images.githubusercontent.com/19851115/35910721-82936a62-0c1d-11e8-9ab5-7a4837dd3e46.JPG)

**Comment by dgolovin** [comment]
@amitkrout CDK has tested with Virtualbox versions from 5.1.x stream only. The message is not correct saying 'or higher', it supposed to say 'or higher version from 5.1 release stream'.
I am sorry you hit this issues. Would uninstalling Virtualbox 5.2.6 and try to install CDK using DevSuite Installer again be an option for you to resolve this issue?

**Comment by amitkrout** [comment]
@dgolovin Thanks for the comment, My concern is why devsuite doesn't support 5.2.x, Even in the CDK released doc [1] its clearly mentioned that ```Red Hat Container Development Kit 3.3 has been tested with VirtualBox 5.1.14 and higher, ...```, even i have run all the cdk test on Virtualbox 5.2.6. By seeing cdk doc i am having a feeling that devsuite even not in sync with cdk like minimum VirtualBox supported version ```(CDK - VirtualBox 5.1.14  and Devsuite - VirtualBox 5.1.22)``` 

[1] https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.3/html/release_notes_and_known_issues/release_notes#virtualbox_compatibility

**Comment by dgolovin** [comment]
@amitkrout I'll discuss that with CDK team and get that fixed in new sprint. We seems got out of sync and that should be fixed. Thanks for rising this issues.

**Comment by elexpander** [comment]
Just met this issue with VirtualBox 5.2.8 :/

**Comment by dgolovin** [comment]
@elexpander Sorry you have this issue. Right now the only workaround is to stick to [manual CDK installation](https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.3/html/getting_started_guide/getting_started_with_container_development_kit#quickstart).

**Comment by jrichter1** [comment]
fixed in 3712a31
