### ISSUE TITLE
The CDK install process for a new user is not curated

### ISSUE THREAD

**Issue by JimTyrrell** [redhat-developer-tooling/developer-platform-install#1260]
As a new user, running the install gets me to a page that asks me to click a link.

This link is the same page that I downloaded the installer from, now what do I do as a Developer.  Where should that feedback go, and how do we have a conversation around these challenges?

**Comment by JimTyrrell** [comment]
Specifically the end of the install looks like this:
<img width="989" alt="screen shot 2018-02-07 at 9 13 11 am" src="https://user-images.githubusercontent.com/4389749/35927129-2f54647c-0be7-11e8-9005-a51e420ba050.png">

Sends me to this URL and isn't a very curated experience.
https://developers.redhat.com/products/devsuite/hello-world/

First issue, is it doesn't figure out my OS and target the right tab.

Second issue, is what do I do next?  I get put at the top of the page, to redo all of the steps I just did.

When I scroll to step 3, and click on the CDK link I get to a page:
https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.3/html-single/getting_started_guide/index/index.html

Which is pages upon pages of installing OpenShift.  Didn't I just do that.

In user experience evaluation this kind of experience "erodes the users trust" on them deciding to continue to use and recommend the product.

**Comment by dgolovin** [comment]
@JimTyrrell Thank you for letting us know about your user experience with Installer. This is our top priority for next release to fix issues like this.  

We are going to improve Installer's final page and provide info related to installed tools that would curate new user what to do next.

Also we are going to introduce a concept of 'Guided Development' or 'Curated Development'. It would let users to install predefined set of development tools (based on DevStudio for now) and run-times, run DevStudio from final installer page and curate development process for simple Hello World project with automatically triggered Eclipse cheat sheet.

**Comment by JimTyrrell** [comment]
@dgolovin Happy to help in any way I can.  Just let me know!!!

**Comment by dgolovin** [comment]
Resolved via:
* Final Page new design #1321 
* Displaying dependents for featured installed components #1360 
* Updating link for CDK #1357
