### ISSUE TITLE
Launch Installer e2e tests on Windows with a space in username

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#1277]
There was several issues/regressions for this usecase. it would be nice to have the test launched in this configuration.

Nota: it might be good to test also with some UTF-8 special characters.

Migrated form https://issues.jboss.org/browse/JBDS-4673

**Comment by dgolovin** [comment]
@jrichter1 this is something that worth to do for DevSuite Installer as well.

**Comment by jrichter1** [comment]
CI updated, job created, tests run.
