### ISSUE TITLE
JDK not found on macOS

### ISSUE THREAD

**Issue by pcd4h** [redhat-developer-tooling/developer-platform-install#1336]
The installer doesn't see the JDK that's already installed on the machine. It's still displaying the message 'You have selected Red Hat JBoss Developer Studio, which requires Oracle Java version 1.8.0 or higher. Due to licence limitations we may not install Java for you. Please install JDK version 1.8.0 downloaded from this location and restart the Installer to continue'.
It is still displayed after re-installation of JDK.

**Comment by dgolovin** [comment]
Sorry you have this issue. 
What is output for `/usr/libexec/java_home'?

**Comment by timuluvus** [comment]
I have this same issue. Has anyone been able to resolve it? Have tried to install JDK several times and when check java -version on mac, everything is as expected.

**Comment by timuluvus** [comment]
Output of java_home is: /Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home

**Comment by jrichter1** [comment]
In case you have java 9 or 10 installed, beware, the error message is misleading. The only java version that does work here is java 8 (or 1.8). And it only works if java 8 is the default java on your system.

Which leaves a question for @dgolovin: 
 Add support for newer java (eclipse seems to run fine on it)
 -- OR --
 Make it clear java 1.8 is the desired version and make sure it is found even if it is not the default

**Comment by timuluvus** [comment]
OK I uninstalled java and installed JDK Java SE 8u161 (http://www.oracle.com/technetwork/java/javase/downloads/index.html). The requirement for 1.8.0 or higher in the error message is misleading.

**Comment by dgolovin** [comment]
@jrichter1 Thanks! 
@timuluvus @pcd4h Thank you for update, unfortunately @jrichter1 is right. 
Will fix detection for newest Java releases first and update error message to be clear that Java 8 is the one to use for now.
Then we will add support for newest Java Releases.
