### ISSUE TITLE
Installer Final Page is empty if nether DevStudio nor CDK are installed

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#1340]
![image](https://user-images.githubusercontent.com/620330/38011886-0ac871ae-3214-11e8-8ee4-aaa8e826bdb3.png)

and final page looks like 

![image](https://user-images.githubusercontent.com/620330/38011894-153f973e-3214-11e8-8ec0-2462b6e444f5.png)

We have UI for DevStudio and CDK if installed. There should additional group on final page to aggregate independent components like compose or Red Hat AMT CLI.

**Comment by jrichter1** [comment]
And what happened to the close/finish button?

**Comment by dgolovin** [comment]
Good point @jrichter1, it is vanished out of existence.
@mohitsuman please, return button back.

**Comment by mohitsuman** [comment]
Add Close Button to installer final page. #1371
