### ISSUE TITLE
Weird progress status

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer-tooling/developer-platform-install#908]
This happened on mac when CDK was installing and a detected virtualbox was being used. Also it was a bundled installer.

![screen shot 2017-10-10 at 15 33 19](https://user-images.githubusercontent.com/4181232/31425438-a2c2a788-ae5f-11e7-8681-d7de031cbcbb.png)

Even though it was 'waiting for itself to install' it actually finished successfully.

**Comment by dgolovin** [comment]
It seems to be macOS specific and replicates only when CDK installed with requirements fulfilled.

**Comment by dgolovin** [comment]
Was able to replicate for the case when Virtualbox detected and I continued installation with components selected by default. Installation finished successfully though. It clearly indicates some problems with progress bar updates. That can also happen on windows.
