### ISSUE TITLE
Downloaded components posing as not downloaded

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer-tooling/developer-platform-install#909]
Some components never seem to act like they have been downloaded. The file sizes might be wrong.

**Comment by jrichter1** [comment]
The sizes don't match, I'm going to keep this open as a reminder for when we update to the release candidates.

**Comment by jrichter1** [comment]
And strangely enough, it looks like some files actually return different sizes on different systems.

**Comment by mohitsuman** [comment]
@jrichter1 Which components are these, I will check them individually for the file size.

**Comment by jrichter1** [comment]
@mohitsuman from what I've experienced, it was:  devstudio, CDK (mac only), kompose and fuse platform (EAP one)
The really weird thing though, fs.stat returns different size for devstudio for each OS I've tried, even though it is the same file

**Comment by dgolovin** [comment]
could that be related to node.js version we use to build in Central CI?

**Comment by jrichter1** [comment]
@dgolovin all fs.stat does is call the appropriate stat function from the terminal and put the results into an object
And from what I have seen, different OSes (or indeed different file systems) just return slightly different values.

For example, what stat returns for devstudio:
 - mac 11.15.4: 677694419
 - win10: 677689480

**Comment by dgolovin** [comment]
Problem is `mkdirp.sync(this.downloadFolder);` call inside InstallableItem constructor. It has different behavior between mac and windows. On windows if targeted folder exists execution continues, on mac it throws exception. It means everything is fine for first execution when no cache folder and it starts to behave wrong for all consecutive times.

**Comment by jrichter1** [comment]
Fuse on EAP still has a different size to what is in requirements.json for me. Anyone care to verify?

**Comment by dgolovin** [comment]
I'll check it, it is probably related to fact that Fuse on EAP is downloading two files under the hood, not one.

**Comment by mohitsuman** [comment]
On macOS, these are the 2 files which are getting downloaded & installed.
__fuse-eap-installer-6.3.0.redhat-187.jar_ :  234.9 MB
_jboss-eap-6.4.0.GA-installer.ja_r  : 201.3 MB

On the UI selection page, it shows **217.49 MB.**

**Comment by dgolovin** [comment]
@mohitsuman Problem is even it is downloaded it is still marked as `Selected for download`, could you confirm that?

**Comment by mohitsuman** [comment]
@dgolovin Yeah it is marked as `Selected for download`.

**Comment by dgolovin** [comment]
I've opened issue specific to components that require more than one resource to download https://github.com/redhat-developer-tooling/developer-platform-install/issues/995
