### ISSUE TITLE
Add Eclipse Che installer

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer-tooling/developer-platform-install#911]
Add Eclipse Che to the list of components available for installation assuming we are going to achieve this with CDK add-on. It means Che installer will require CDK and enable CDK add-on during installation.  
- [X]     Create empty installer and add Che into list of components (https://github.com/redhat-developer-tooling/developer-platform-install/pull/913)
- [X]     Implement Che add-on (https://github.com/minishift/minishift-addons/pull/43)
- [x]     Install Che add-on in CDK
- [x]     Implement installer for Che that enables 'che' add on on CDKE
- [ ]     Add link to documentation how to start and use Eclipse Che

**Comment by gbraad** [comment]
The add-on (https://github.com/minishift/minishift-addons/pull/43) is expected to be merged soon.

**Comment by LalatenduMohanty** [comment]
> his however will probably be an installed add-on for CDK (only enable to install on startup is needed?). /cc: @LalatenduMohanty

Right. Devsuite need to enable this, set the memory to 5GB and then instruct the user to start `minishift`.

 i.e. 
```
$ minishift config set memory 5GB
$ minishift addon enable \<che-add-on\>
```
Then user to do `minishift start`.

**Comment by gbraad** [comment]
do we run as `anyuid` or not?

**Comment by dgolovin** [comment]
Thanks @LalatenduMohanty!
I assume the name for add-on would be just `che', is that right?

**Comment by gbraad** [comment]
Yes. The addon itself will be identified by the name `che`.
