### ISSUE TITLE
Possible localization issue when adding user to Hyper-V Administrators group

### ISSUE THREAD

**Issue by gbraad** [redhat-developer-tooling/developer-platform-install#930]
https://github.com/redhat-developer-tooling/developer-platform-install/blob/5ec2f16dab28877f0d4cac09b1f6261e1c7c215b/browser/model/cdk.js#L48

this line refers to the group by string, instead of a security ID. This has caused issues on Minishift, see: https://github.com/minishift/minishift/issues/1541

When using a different locale, like pt-BR this group is called: "Administradores do Hyper-V"

**Comment by dgolovin** [comment]
@gbraad thank you for reviewing CDK Installer code!

**Comment by gbraad** [comment]
@dgolovin this is to be expected as we need to provide a consistent message to our users ;-)
