### ISSUE TITLE
Remember Me checkbox should work in case local storage is deleted

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer-tooling/developer-platform-install#992]
Steps to reproduce:
1. Remove cache and keep `settings.json` file.
2. Delete `localstorage` entry for checkbox from the app.
3. Run the installer

Observation:
The username and password fields are there, but the checkbox is unchecked (as there is no localstorage entry).

**Comment by dgolovin** [comment]
@mohitsuman @sudhirverma could you update description with steps to reproduce the issue?

**Comment by mohitsuman** [comment]
@dgolovin I have update the description of the issue. This was reproducible for me on macOS.
